# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/rust:1.73.0

    working_directory: /tmp/repo
    steps:
      - checkout
      - run: cargo --version
      - run: 
          name: Run Tests
          command: "cargo test"
      - run: mkdir -p /tmp/artifacts
      - run: rustup target add x86_64-pc-windows-gnu
      - run: 
          name: Build Artifacts
          command: "cargo build --target-dir /tmp/artifacts/ --target x86_64-pc-windows-gnu && cargo build --target-dir /tmp/artifacts/"
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  build-and-store:
    jobs:
      - build
